#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
SD Card Writer for Raspberry Pi Bare Metal Project
SDカードへの自動書き込みツール

必要なファイルをSDカードに書き込み、Raspberry Pi 4用の起動環境を構築します。
"""

import os
import sys
import shutil
import argparse
from pathlib import Path
import platform

try:
    from colorama import Fore, Style, init
    init(autoreset=True)
    HAS_COLOR = True
except ImportError:
    HAS_COLOR = False
    class Fore:
        RED = GREEN = YELLOW = CYAN = BLUE = MAGENTA = WHITE = ""
    class Style:
        RESET_ALL = BRIGHT = ""


class SDCardWriter:
    """SDカード書き込みクラス"""
    
    def __init__(self, project_root=None):
        """
        初期化
        
        Args:
            project_root: プロジェクトルートディレクトリ（未指定時は自動検出）
        """
        if project_root:
            self.project_root = Path(project_root).resolve()
        else:
            # スクリプトの親ディレクトリをプロジェクトルートとする
            self.project_root = Path(__file__).parent.parent.resolve()
        
        self.firmware_dir = self.project_root / "firmware" / "boot"
        self.build_output = self.project_root / "build" / "output"
        self.kernel_img = self.build_output / "kernel.img"
        
        # 必須ブートファイル（Raspberry Pi 4用）
        self.required_boot_files = [
            "bootcode.bin",
            "start4.elf",
            "fixup4.dat"
        ]
        
    def print_info(self, message):
        """情報メッセージを表示"""
        print(f"{Fore.CYAN}[INFO]{Style.RESET_ALL} {message}")
    
    def print_success(self, message):
        """成功メッセージを表示"""
        print(f"{Fore.GREEN}[SUCCESS]{Style.RESET_ALL} {message}")
    
    def print_warning(self, message):
        """警告メッセージを表示"""
        print(f"{Fore.YELLOW}[WARNING]{Style.RESET_ALL} {message}")
    
    def print_error(self, message):
        """エラーメッセージを表示"""
        print(f"{Fore.RED}[ERROR]{Style.RESET_ALL} {message}")
    
    def check_prerequisites(self):
        """必須ファイルの存在確認"""
        errors = []
        
        # kernel.imgの確認
        if not self.kernel_img.exists():
            errors.append(f"kernel.img が見つかりません: {self.kernel_img}")
            errors.append("  -> build/build.bat または build.sh を実行してビルドしてください")
        
        # ファームウェアディレクトリの確認
        if not self.firmware_dir.exists():
            errors.append(f"ファームウェアディレクトリが見つかりません: {self.firmware_dir}")
        else:
            # 必須ブートファイルの確認
            for boot_file in self.required_boot_files:
                boot_path = self.firmware_dir / boot_file
                if not boot_path.exists():
                    errors.append(f"必須ブートファイルが見つかりません: {boot_file}")
        
        if errors:
            self.print_error("前提条件チェックに失敗しました:")
            for error in errors:
                print(f"  {error}")
            return False
        
        return True
    
    def list_drives(self):
        """利用可能なドライブを一覧表示（Windows）"""
        if platform.system() != "Windows":
            self.print_warning("このオプションはWindows専用です")
            return
        
        print("\n" + "=" * 60)
        print(" 利用可能なドライブ")
        print("=" * 60)
        
        # Windows: wmic コマンドでリムーバブルドライブを検出
        import subprocess
        try:
            result = subprocess.run(
                ['wmic', 'logicaldisk', 'get', 'caption,volumename,drivetype'],
                capture_output=True,
                text=True,
                encoding='cp932'  # Windows日本語環境対応
            )
            
            if result.returncode == 0:
                lines = result.stdout.strip().split('\n')
                print(f"\n{Fore.CYAN}検出されたドライブ:{Style.RESET_ALL}")
                for line in lines[1:]:  # ヘッダーをスキップ
                    if line.strip():
                        parts = line.split()
                        if len(parts) >= 2:
                            drive = parts[0]
                            drive_type = parts[-1]
                            # DriveType 2 = Removable
                            if drive_type == '2':
                                print(f"  {Fore.GREEN}[リムーバブル]{Style.RESET_ALL} {drive}")
                            else:
                                print(f"  {drive} (DriveType: {drive_type})")
        except Exception as e:
            self.print_warning(f"ドライブ検出エラー: {e}")
        
        print("\n" + "=" * 60)
        print(f"{Fore.YELLOW}注意: 必ずリムーバブルドライブ（SDカード）を選択してください{Style.RESET_ALL}")
        print("=" * 60 + "\n")
    
    def create_config_txt(self, use_hdmi=True, enable_uart=False):
        """
        config.txtファイルを生成
        
        Args:
            use_hdmi: HDMI出力を使用するか
            enable_uart: UART通信を有効にするか
        
        Returns:
            str: config.txtの内容
        """
        config_lines = [
            "# Raspberry Pi 4 Configuration for Bare Metal",
            "# Generated by sd_writer.py",
            "",
            "# ARMモード（32-bit）",
            "arm_64bit=0",
            "kernel=kernel.img",
            "kernel_address=0x8000",
            "",
        ]
        
        if use_hdmi:
            config_lines.extend([
                "# HDMI設定",
                "hdmi_safe=1",
                "hdmi_force_hotplug=1",
                "",
                "# GPU メモリ（フレームバッファ用）",
                "gpu_mem=64",
                "",
            ])
        
        if enable_uart:
            config_lines.extend([
                "# UART設定",
                "enable_uart=1",
                "dtoverlay=disable-bt",
                "",
            ])
        
        config_lines.extend([
            "# オーバークロック（任意・コメントアウト）",
            "#arm_freq=1800",
            "#over_voltage=2",
            ""
        ])
        
        return "\n".join(config_lines)
    
    def write_to_sd(self, target_drive, use_hdmi=True, enable_uart=False, dry_run=False):
        """
        SDカードに書き込み
        
        Args:
            target_drive: ターゲットドライブパス（例: "E:" または "E:\\"）
            use_hdmi: HDMI出力を使用
            enable_uart: UART通信を有効化
            dry_run: ドライラン（実際には書き込まない）
        
        Returns:
            bool: 成功/失敗
        """
        # ドライブパスの正規化
        target_path = Path(target_drive)
        if not target_path.is_absolute():
            # "E:" -> "E:\\" に変換
            target_path = Path(f"{target_drive}\\")
        
        # ドライブの存在確認
        if not dry_run and not target_path.exists():
            self.print_error(f"指定されたドライブが見つかりません: {target_path}")
            return False
        
        print("\n" + "=" * 60)
        print(f" SDカード書き込み {'[ドライラン]' if dry_run else ''}")
        print("=" * 60)
        print(f"ターゲット: {target_path}")
        print(f"HDMI出力: {'有効' if use_hdmi else '無効'}")
        print(f"UART通信: {'有効' if enable_uart else '無効'}")
        print("=" * 60 + "\n")
        
        # 確認
        if not dry_run:
            response = input(f"{Fore.YELLOW}上記の設定でSDカードに書き込みますか？ (yes/no): {Style.RESET_ALL}")
            if response.lower() not in ['yes', 'y']:
                self.print_info("キャンセルされました")
                return False
        
        files_to_copy = []
        
        # 1. ブートファイルのコピー
        self.print_info("ブートファイルをコピーします...")
        for boot_file in self.required_boot_files:
            src = self.firmware_dir / boot_file
            dst = target_path / boot_file
            files_to_copy.append((src, dst, boot_file))
        
        # 2. kernel.imgのコピー
        self.print_info("kernel.imgをコピーします...")
        files_to_copy.append((self.kernel_img, target_path / "kernel.img", "kernel.img"))
        
        # ファイルコピー実行
        for src, dst, name in files_to_copy:
            try:
                if dry_run:
                    self.print_info(f"[DRY-RUN] {name} -> {dst}")
                else:
                    shutil.copy2(src, dst)
                    self.print_success(f"コピー完了: {name}")
            except Exception as e:
                self.print_error(f"{name} のコピーに失敗: {e}")
                return False
        
        # 3. config.txtの生成
        self.print_info("config.txtを生成します...")
        config_content = self.create_config_txt(use_hdmi, enable_uart)
        config_path = target_path / "config.txt"
        
        try:
            if dry_run:
                self.print_info(f"[DRY-RUN] config.txt -> {config_path}")
                print("\n--- config.txt 内容 ---")
                print(config_content)
                print("--- END ---\n")
            else:
                with open(config_path, 'w', encoding='utf-8') as f:
                    f.write(config_content)
                self.print_success("config.txt を生成しました")
        except Exception as e:
            self.print_error(f"config.txtの生成に失敗: {e}")
            return False
        
        print("\n" + "=" * 60)
        if dry_run:
            self.print_info("ドライラン完了（実際の書き込みは行われていません）")
        else:
            self.print_success("SDカードへの書き込みが完了しました！")
        print("=" * 60)
        
        if not dry_run:
            print(f"\n{Fore.GREEN}次のステップ:{Style.RESET_ALL}")
            print("  1. SDカードを安全に取り外す")
            print("  2. Raspberry Pi 4に挿入")
            print("  3. 電源を投入")
            if enable_uart:
                print("  4. シリアルモニター（serial_monitor.py）で動作確認")
            if use_hdmi:
                print("  4. HDMIディスプレイで出力を確認")
        
        return True


def main():
    """メイン処理"""
    parser = argparse.ArgumentParser(
        description="Raspberry Pi 4用SDカード書き込みツール",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
使用例:
  # ドライブ一覧を表示（Windows）
  python sd_writer.py --list
  
  # E:ドライブに書き込み（HDMI出力使用）
  python sd_writer.py --drive E: --hdmi
  
  # E:ドライブに書き込み（UART通信使用）
  python sd_writer.py --drive E: --uart
  
  # ドライラン（実際には書き込まない）
  python sd_writer.py --drive E: --hdmi --dry-run
        """
    )
    
    parser.add_argument(
        '--list', '-l',
        action='store_true',
        help='利用可能なドライブを一覧表示（Windows）'
    )
    
    parser.add_argument(
        '--drive', '-d',
        type=str,
        help='ターゲットドライブ（例: E: または /media/sdcard）'
    )
    
    parser.add_argument(
        '--hdmi',
        action='store_true',
        default=True,
        help='HDMI出力を有効化（デフォルト: 有効）'
    )
    
    parser.add_argument(
        '--no-hdmi',
        action='store_true',
        help='HDMI出力を無効化'
    )
    
    parser.add_argument(
        '--uart',
        action='store_true',
        default=False,
        help='UART通信を有効化'
    )
    
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='ドライラン（実際には書き込まない）'
    )
    
    parser.add_argument(
        '--project-root',
        type=str,
        help='プロジェクトルートディレクトリ（通常は自動検出）'
    )
    
    args = parser.parse_args()
    
    # HDMIフラグの調整
    use_hdmi = args.hdmi and not args.no_hdmi
    
    # SDCardWriterインスタンス作成
    writer = SDCardWriter(args.project_root)
    
    print("\n" + "=" * 60)
    print(f" {Fore.CYAN}Raspberry Pi 4 SDカード書き込みツール{Style.RESET_ALL}")
    print("=" * 60)
    print(f"プロジェクトルート: {writer.project_root}")
    print("=" * 60 + "\n")
    
    # ドライブ一覧表示モード
    if args.list:
        writer.list_drives()
        return 0
    
    # 書き込みモード
    if not args.drive:
        print(f"{Fore.RED}エラー: --drive オプションが必要です{Style.RESET_ALL}")
        print("使用方法: python sd_writer.py --drive E: --hdmi")
        print("または: python sd_writer.py --list でドライブ一覧を表示")
        return 1
    
    # 前提条件チェック
    if not writer.check_prerequisites():
        return 1
    
    # SDカードに書き込み
    success = writer.write_to_sd(
        args.drive,
        use_hdmi=use_hdmi,
        enable_uart=args.uart,
        dry_run=args.dry_run
    )
    
    return 0 if success else 1


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print(f"\n{Fore.YELLOW}中断されました{Style.RESET_ALL}")
        sys.exit(1)
    except Exception as e:
        print(f"\n{Fore.RED}エラー: {e}{Style.RESET_ALL}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
